# Generated by Django 4.1.7 on 2023-05-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='element_selector',
        ),
        migrations.RemoveField(
            model_name='scrapeddata',
            name='element_type',
        ),
        migrations.RemoveField(
            model_name='scrapeddata',
            name='scraped_data',
        ),
    ]
