# Generated by Django 4.1.7 on 2023-05-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_scrapeddata_element_selector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='name_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
